In [4]:
import os
import pandas as pd

In [14]:
# Configurando o caminho para armazenar os arquivos csv
os.makedirs('C:/Users/nobuy/Documents/cursos/Cursos_DataCamp/introdu-o-ao-PySpark-Curso-DataCamp', exist_ok=True)

In [15]:
# Lendo os datasets em formato csv
airports = pd.read_csv("https://assets.datacamp.com/production/repositories/1237/datasets/6e5c4ac2a4799338ba7e13d54ce1fa918da644ba/airports.csv")
flights = pd.read_csv('https://assets.datacamp.com/production/repositories/1237/datasets/fa47bb54e83abd422831cbd4f441bd30fd18bd15/flights_small.csv')
planes = pd.read_csv('https://assets.datacamp.com/production/repositories/1237/datasets/231480a2696c55fde829ce76d936596123f12c0c/planes.csv')

In [16]:
airports.head(10)

   faa                            name        lat         lon   alt  tz dst
0  04G               Lansdowne Airport  41.130472  -80.619583  1044  -5   A
1  06A   Moton Field Municipal Airport  32.460572  -85.680028   264  -5   A
2  06C             Schaumburg Regional  41.989341  -88.101243   801  -6   A
3  06N                 Randall Airport  41.431912  -74.391561   523  -5   A
4  09J           Jekyll Island Airport  31.074472  -81.427778    11  -4   A
5  0A9  Elizabethton Municipal Airport  36.371222  -82.173417  1593  -4   A
6  0G6         Williams County Airport  41.467306  -84.506778   730  -5   A
7  0G7   Finger Lakes Regional Airport  42.883565  -76.781232   492  -5   A
8  0P2    Shoestring Aviation Airfield  39.794824  -76.647191  1000  -5   U
9  0S9           Jefferson County Intl  48.053809 -122.810644   108  -8   A

In [17]:
flights.head(10)

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2014,12,8,658.0,-7.0,935.0,-5.0,VX,N846VA,1780,SEA,LAX,132.0,954,6.0,58.0
1,2014,1,22,1040.0,5.0,1505.0,5.0,AS,N559AS,851,SEA,HNL,360.0,2677,10.0,40.0
2,2014,3,9,1443.0,-2.0,1652.0,2.0,VX,N847VA,755,SEA,SFO,111.0,679,14.0,43.0
3,2014,4,9,1705.0,45.0,1839.0,34.0,WN,N360SW,344,PDX,SJC,83.0,569,17.0,5.0
4,2014,3,9,754.0,-1.0,1015.0,1.0,AS,N612AS,522,SEA,BUR,127.0,937,7.0,54.0
5,2014,1,15,1037.0,7.0,1352.0,2.0,WN,N646SW,48,PDX,DEN,121.0,991,10.0,37.0
6,2014,7,2,847.0,42.0,1041.0,51.0,WN,N422WN,1520,PDX,OAK,90.0,543,8.0,47.0
7,2014,5,12,1655.0,-5.0,1842.0,-18.0,VX,N361VA,755,SEA,SFO,98.0,679,16.0,55.0
8,2014,4,19,1236.0,-4.0,1508.0,-7.0,AS,N309AS,490,SEA,SAN,135.0,1050,12.0,36.0
9,2014,11,19,1812.0,-3.0,2352.0,-4.0,AS,N564AS,26,SEA,ORD,198.0,1721,18.0,12.0

In [18]:
planes.head(10)

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
1,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,N104UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
3,N105UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
4,N107US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
5,N108UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
6,N109UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
7,N110UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
8,N111US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
9,N11206,2000.0,Fixed wing multi engine,BOEING,737-824,2,149,NaN,Turbo-fan

In [21]:
# Carregando os datasets para o disco local em formato csv
airports.to_csv('C:/Users/nobuy/Documents/cursos/Cursos_DataCamp/introdu-o-ao-PySpark-Curso-DataCamp/data/airports.csv')
flights.to_csv('C:/Users/nobuy/Documents/cursos/Cursos_DataCamp/introdu-o-ao-PySpark-Curso-DataCamp/data/flights.csv')
planes.to_csv('C:/Users/nobuy/Documents/cursos/Cursos_DataCamp/introdu-o-ao-PySpark-Curso-DataCamp/data/planes.csv')